// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stwartchain/polls/options.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Options struct {
	Id           uint64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VotersCount  uint64       `protobuf:"varint,2,opt,name=votersCount,proto3" json:"votersCount,omitempty"`
	TokensAmount []types.Coin `protobuf:"bytes,3,rep,name=tokensAmount,proto3" json:"tokensAmount"`
	IsVeto       bool         `protobuf:"varint,4,opt,name=isVeto,proto3" json:"isVeto,omitempty"`
	Text         string       `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	IsWinner     bool         `protobuf:"varint,6,opt,name=isWinner,proto3" json:"isWinner,omitempty"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_ade00bcdb735b05c, []int{0}
}
func (m *Options) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Options.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return m.Size()
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Options) GetVotersCount() uint64 {
	if m != nil {
		return m.VotersCount
	}
	return 0
}

func (m *Options) GetTokensAmount() []types.Coin {
	if m != nil {
		return m.TokensAmount
	}
	return nil
}

func (m *Options) GetIsVeto() bool {
	if m != nil {
		return m.IsVeto
	}
	return false
}

func (m *Options) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Options) GetIsWinner() bool {
	if m != nil {
		return m.IsWinner
	}
	return false
}

func init() {
	proto.RegisterType((*Options)(nil), "stwartchain.polls.Options")
}

func init() { proto.RegisterFile("stwartchain/polls/options.proto", fileDescriptor_ade00bcdb735b05c) }

var fileDescriptor_ade00bcdb735b05c = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4e, 0x2a, 0x31,
	0x14, 0x86, 0xa7, 0x30, 0x97, 0x8b, 0xc5, 0x98, 0xd8, 0x18, 0x33, 0xb2, 0x28, 0x13, 0x57, 0xb3,
	0xb1, 0x0d, 0xfa, 0x04, 0xc0, 0x03, 0x98, 0xcc, 0x42, 0x13, 0x5d, 0x75, 0x86, 0x06, 0x2a, 0x43,
	0xcf, 0x64, 0x7a, 0x44, 0x7c, 0x0b, 0x1f, 0x8b, 0x25, 0x4b, 0x57, 0xc6, 0xc0, 0x8b, 0x98, 0xe9,
	0x10, 0x83, 0xbb, 0x73, 0xfa, 0x7f, 0xa7, 0x7f, 0xf2, 0xd1, 0x81, 0xc3, 0x37, 0x55, 0x61, 0x3e,
	0x57, 0xc6, 0xca, 0x12, 0x8a, 0xc2, 0x49, 0x28, 0xd1, 0x80, 0x75, 0xa2, 0xac, 0x00, 0x81, 0x9d,
	0x1f, 0x01, 0xc2, 0x03, 0xfd, 0x8b, 0x19, 0xcc, 0xc0, 0xa7, 0xb2, 0x9e, 0x1a, 0xb0, 0xcf, 0x73,
	0x70, 0x4b, 0x70, 0x32, 0x53, 0x4e, 0xcb, 0xd5, 0x30, 0xd3, 0xa8, 0x86, 0x32, 0x87, 0xfa, 0xaa,
	0xce, 0xaf, 0x37, 0x84, 0xfe, 0xbf, 0x6f, 0xbe, 0x66, 0x67, 0xb4, 0x65, 0xa6, 0x11, 0x89, 0x49,
	0x12, 0xa6, 0x2d, 0x33, 0x65, 0x31, 0xed, 0xad, 0x00, 0x75, 0xe5, 0x26, 0xf0, 0x6a, 0x31, 0x6a,
	0xf9, 0xe0, 0xf8, 0x89, 0x4d, 0xe8, 0x29, 0xc2, 0x42, 0x5b, 0x37, 0x5a, 0x7a, 0xa4, 0x1d, 0xb7,
	0x93, 0xde, 0xed, 0x95, 0x68, 0x4a, 0x45, 0x5d, 0x2a, 0x0e, 0xa5, 0x62, 0x02, 0xc6, 0x8e, 0xc3,
	0xcd, 0xd7, 0x20, 0x48, 0xff, 0x1c, 0xb1, 0x4b, 0xda, 0x31, 0xee, 0x41, 0x23, 0x44, 0x61, 0x4c,
	0x92, 0x6e, 0x7a, 0xd8, 0x18, 0xa3, 0x21, 0xea, 0x35, 0x46, 0xff, 0x62, 0x92, 0x9c, 0xa4, 0x7e,
	0x66, 0x7d, 0xda, 0x35, 0xee, 0xd1, 0x58, 0xab, 0xab, 0xa8, 0xe3, 0xe9, 0xdf, 0x7d, 0xfc, 0xbc,
	0xd9, 0x71, 0xb2, 0xdd, 0x71, 0xf2, 0xbd, 0xe3, 0xe4, 0x63, 0xcf, 0x83, 0xed, 0x9e, 0x07, 0x9f,
	0x7b, 0x1e, 0x3c, 0x8d, 0x66, 0x06, 0x0b, 0x95, 0x09, 0x87, 0xaa, 0xa8, 0xb5, 0x09, 0xd4, 0xf9,
	0x5c, 0x9a, 0x17, 0x03, 0x72, 0x59, 0x1b, 0xce, 0x54, 0xbe, 0xd0, 0x76, 0x2a, 0x1b, 0xa9, 0x37,
	0x8d, 0xf6, 0xf5, 0x41, 0x3c, 0xbe, 0x97, 0xda, 0x65, 0x1d, 0xaf, 0xeb, 0xee, 0x27, 0x00, 0x00,
	0xff, 0xff, 0xfd, 0xb6, 0x19, 0x2c, 0x9a, 0x01, 0x00, 0x00,
}

func (m *Options) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Options) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Options) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsWinner {
		i--
		if m.IsWinner {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.Text) > 0 {
		i -= len(m.Text)
		copy(dAtA[i:], m.Text)
		i = encodeVarintOptions(dAtA, i, uint64(len(m.Text)))
		i--
		dAtA[i] = 0x2a
	}
	if m.IsVeto {
		i--
		if m.IsVeto {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.TokensAmount) > 0 {
		for iNdEx := len(m.TokensAmount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TokensAmount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintOptions(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.VotersCount != 0 {
		i = encodeVarintOptions(dAtA, i, uint64(m.VotersCount))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintOptions(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintOptions(dAtA []byte, offset int, v uint64) int {
	offset -= sovOptions(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Options) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovOptions(uint64(m.Id))
	}
	if m.VotersCount != 0 {
		n += 1 + sovOptions(uint64(m.VotersCount))
	}
	if len(m.TokensAmount) > 0 {
		for _, e := range m.TokensAmount {
			l = e.Size()
			n += 1 + l + sovOptions(uint64(l))
		}
	}
	if m.IsVeto {
		n += 2
	}
	l = len(m.Text)
	if l > 0 {
		n += 1 + l + sovOptions(uint64(l))
	}
	if m.IsWinner {
		n += 2
	}
	return n
}

func sovOptions(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOptions(x uint64) (n int) {
	return sovOptions(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Options) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOptions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Options: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Options: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotersCount", wireType)
			}
			m.VotersCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotersCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokensAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokensAmount = append(m.TokensAmount, types.Coin{})
			if err := m.TokensAmount[len(m.TokensAmount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsVeto", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsVeto = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Text", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOptions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOptions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Text = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsWinner", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsWinner = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipOptions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOptions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOptions(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOptions
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOptions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOptions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOptions
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOptions
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOptions
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOptions        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOptions          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOptions = fmt.Errorf("proto: unexpected end of group")
)
