swagger: '2.0'
info:
  title: HTTP API Console stwartchain.core
  name: ''
  description: ''
paths:
  /backend/stwart-chain/core/modules_addresses:
    get:
      operationId: Query_ModulesAddresses
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              address:
                type: array
                items:
                  type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /stwart/core/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /stwart/core/stats:
    get:
      operationId: Query_StatsAll
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              stats:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                    dailyStats:
                      type: object
                      properties:
                        issuedCoins:
                          type: array
                          items:
                            type: object
                            properties:
                              denom:
                                type: string
                              amount:
                                type: string
                        countIssued:
                          type: string
                          format: uint64
                        burnedCoins:
                          type: array
                          items:
                            type: object
                            properties:
                              denom:
                                type: string
                              amount:
                                type: string
                        countBurned:
                          type: string
                          format: uint64
                        withdrawCoins:
                          type: array
                          items:
                            type: object
                            properties:
                              denom:
                                type: string
                              amount:
                                type: string
                        countWithdraw:
                          type: string
                          format: uint64
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /stwart/core/stats/{date}:
    get:
      operationId: Query_Stats
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              stats:
                type: object
                properties:
                  date:
                    type: string
                  dailyStats:
                    type: object
                    properties:
                      issuedCoins:
                        type: array
                        items:
                          type: object
                          properties:
                            denom:
                              type: string
                            amount:
                              type: string
                      countIssued:
                        type: string
                        format: uint64
                      burnedCoins:
                        type: array
                        items:
                          type: object
                          properties:
                            denom:
                              type: string
                            amount:
                              type: string
                      countBurned:
                        type: string
                        format: uint64
                      withdrawCoins:
                        type: array
                        items:
                          type: object
                          properties:
                            denom:
                              type: string
                            amount:
                              type: string
                      countWithdraw:
                        type: string
                        format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: date
          in: path
          required: true
          type: string
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  Coin:
    type: object
    properties:
      denom:
        type: string
      amount:
        type: string
  DailyStats:
    type: object
    properties:
      issuedCoins:
        type: array
        items:
          type: object
          properties:
            denom:
              type: string
            amount:
              type: string
      countIssued:
        type: string
        format: uint64
      burnedCoins:
        type: array
        items:
          type: object
          properties:
            denom:
              type: string
            amount:
              type: string
      countBurned:
        type: string
        format: uint64
      withdrawCoins:
        type: array
        items:
          type: object
          properties:
            denom:
              type: string
            amount:
              type: string
      countWithdraw:
        type: string
        format: uint64
  PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
      offset:
        type: string
        format: uint64
      limit:
        type: string
        format: uint64
      count_total:
        type: boolean
      reverse:
        type: boolean
  PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
      total:
        type: string
        format: uint64
  QueryAllStatsResponse:
    type: object
    properties:
      stats:
        type: array
        items:
          type: object
          properties:
            date:
              type: string
            dailyStats:
              type: object
              properties:
                issuedCoins:
                  type: array
                  items:
                    type: object
                    properties:
                      denom:
                        type: string
                      amount:
                        type: string
                countIssued:
                  type: string
                  format: uint64
                burnedCoins:
                  type: array
                  items:
                    type: object
                    properties:
                      denom:
                        type: string
                      amount:
                        type: string
                countBurned:
                  type: string
                  format: uint64
                withdrawCoins:
                  type: array
                  items:
                    type: object
                    properties:
                      denom:
                        type: string
                      amount:
                        type: string
                countWithdraw:
                  type: string
                  format: uint64
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryGetStatsResponse:
    type: object
    properties:
      stats:
        type: object
        properties:
          date:
            type: string
          dailyStats:
            type: object
            properties:
              issuedCoins:
                type: array
                items:
                  type: object
                  properties:
                    denom:
                      type: string
                    amount:
                      type: string
              countIssued:
                type: string
                format: uint64
              burnedCoins:
                type: array
                items:
                  type: object
                  properties:
                    denom:
                      type: string
                    amount:
                      type: string
              countBurned:
                type: string
                format: uint64
              withdrawCoins:
                type: array
                items:
                  type: object
                  properties:
                    denom:
                      type: string
                    amount:
                      type: string
              countWithdraw:
                type: string
                format: uint64
  QueryModulesAddressesResponse:
    type: object
    properties:
      address:
        type: array
        items:
          type: string
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  core.Params:
    type: object
  core.Stats:
    type: object
    properties:
      date:
        type: string
      dailyStats:
        type: object
        properties:
          issuedCoins:
            type: array
            items:
              type: object
              properties:
                denom:
                  type: string
                amount:
                  type: string
          countIssued:
            type: string
            format: uint64
          burnedCoins:
            type: array
            items:
              type: object
              properties:
                denom:
                  type: string
                amount:
                  type: string
          countBurned:
            type: string
            format: uint64
          withdrawCoins:
            type: array
            items:
              type: object
              properties:
                denom:
                  type: string
                amount:
                  type: string
          countWithdraw:
            type: string
            format: uint64
  MsgFeesResponse:
    type: object
  MsgIssueResponse:
    type: object
  MsgRefRewardResponse:
    type: object
  MsgRefundResponse:
    type: object
  MsgSendResponse:
    type: object
  MsgUpdateParamsResponse:
    type: object
  MsgWithdrawResponse:
    type: object
  Params:
    type: object
