// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package feepolicy

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var _ protoreflect.List = (*_Tariffs_2_list)(nil)

type _Tariffs_2_list struct {
	list *[]*Tariff
}

func (x *_Tariffs_2_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_Tariffs_2_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_Tariffs_2_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*Tariff)
	(*x.list)[i] = concreteValue
}

func (x *_Tariffs_2_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*Tariff)
	*x.list = append(*x.list, concreteValue)
}

func (x *_Tariffs_2_list) AppendMutable() protoreflect.Value {
	v := new(Tariff)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_Tariffs_2_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_Tariffs_2_list) NewElement() protoreflect.Value {
	v := new(Tariff)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_Tariffs_2_list) IsValid() bool {
	return x.list != nil
}

var (
	md_Tariffs         protoreflect.MessageDescriptor
	fd_Tariffs_denom   protoreflect.FieldDescriptor
	fd_Tariffs_tariffs protoreflect.FieldDescriptor
	fd_Tariffs_creator protoreflect.FieldDescriptor
)

func init() {
	file_stwartchain_feepolicy_tariffs_proto_init()
	md_Tariffs = File_stwartchain_feepolicy_tariffs_proto.Messages().ByName("Tariffs")
	fd_Tariffs_denom = md_Tariffs.Fields().ByName("denom")
	fd_Tariffs_tariffs = md_Tariffs.Fields().ByName("tariffs")
	fd_Tariffs_creator = md_Tariffs.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_Tariffs)(nil)

type fastReflection_Tariffs Tariffs

func (x *Tariffs) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Tariffs)(x)
}

func (x *Tariffs) slowProtoReflect() protoreflect.Message {
	mi := &file_stwartchain_feepolicy_tariffs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Tariffs_messageType fastReflection_Tariffs_messageType
var _ protoreflect.MessageType = fastReflection_Tariffs_messageType{}

type fastReflection_Tariffs_messageType struct{}

func (x fastReflection_Tariffs_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Tariffs)(nil)
}
func (x fastReflection_Tariffs_messageType) New() protoreflect.Message {
	return new(fastReflection_Tariffs)
}
func (x fastReflection_Tariffs_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Tariffs
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Tariffs) Descriptor() protoreflect.MessageDescriptor {
	return md_Tariffs
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Tariffs) Type() protoreflect.MessageType {
	return _fastReflection_Tariffs_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Tariffs) New() protoreflect.Message {
	return new(fastReflection_Tariffs)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Tariffs) Interface() protoreflect.ProtoMessage {
	return (*Tariffs)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Tariffs) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Denom != "" {
		value := protoreflect.ValueOfString(x.Denom)
		if !f(fd_Tariffs_denom, value) {
			return
		}
	}
	if len(x.Tariffs) != 0 {
		value := protoreflect.ValueOfList(&_Tariffs_2_list{list: &x.Tariffs})
		if !f(fd_Tariffs_tariffs, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_Tariffs_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Tariffs) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "stwartchain.feepolicy.Tariffs.denom":
		return x.Denom != ""
	case "stwartchain.feepolicy.Tariffs.tariffs":
		return len(x.Tariffs) != 0
	case "stwartchain.feepolicy.Tariffs.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: stwartchain.feepolicy.Tariffs"))
		}
		panic(fmt.Errorf("message stwartchain.feepolicy.Tariffs does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Tariffs) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "stwartchain.feepolicy.Tariffs.denom":
		x.Denom = ""
	case "stwartchain.feepolicy.Tariffs.tariffs":
		x.Tariffs = nil
	case "stwartchain.feepolicy.Tariffs.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: stwartchain.feepolicy.Tariffs"))
		}
		panic(fmt.Errorf("message stwartchain.feepolicy.Tariffs does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Tariffs) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "stwartchain.feepolicy.Tariffs.denom":
		value := x.Denom
		return protoreflect.ValueOfString(value)
	case "stwartchain.feepolicy.Tariffs.tariffs":
		if len(x.Tariffs) == 0 {
			return protoreflect.ValueOfList(&_Tariffs_2_list{})
		}
		listValue := &_Tariffs_2_list{list: &x.Tariffs}
		return protoreflect.ValueOfList(listValue)
	case "stwartchain.feepolicy.Tariffs.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: stwartchain.feepolicy.Tariffs"))
		}
		panic(fmt.Errorf("message stwartchain.feepolicy.Tariffs does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Tariffs) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "stwartchain.feepolicy.Tariffs.denom":
		x.Denom = value.Interface().(string)
	case "stwartchain.feepolicy.Tariffs.tariffs":
		lv := value.List()
		clv := lv.(*_Tariffs_2_list)
		x.Tariffs = *clv.list
	case "stwartchain.feepolicy.Tariffs.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: stwartchain.feepolicy.Tariffs"))
		}
		panic(fmt.Errorf("message stwartchain.feepolicy.Tariffs does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Tariffs) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "stwartchain.feepolicy.Tariffs.tariffs":
		if x.Tariffs == nil {
			x.Tariffs = []*Tariff{}
		}
		value := &_Tariffs_2_list{list: &x.Tariffs}
		return protoreflect.ValueOfList(value)
	case "stwartchain.feepolicy.Tariffs.denom":
		panic(fmt.Errorf("field denom of message stwartchain.feepolicy.Tariffs is not mutable"))
	case "stwartchain.feepolicy.Tariffs.creator":
		panic(fmt.Errorf("field creator of message stwartchain.feepolicy.Tariffs is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: stwartchain.feepolicy.Tariffs"))
		}
		panic(fmt.Errorf("message stwartchain.feepolicy.Tariffs does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Tariffs) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "stwartchain.feepolicy.Tariffs.denom":
		return protoreflect.ValueOfString("")
	case "stwartchain.feepolicy.Tariffs.tariffs":
		list := []*Tariff{}
		return protoreflect.ValueOfList(&_Tariffs_2_list{list: &list})
	case "stwartchain.feepolicy.Tariffs.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: stwartchain.feepolicy.Tariffs"))
		}
		panic(fmt.Errorf("message stwartchain.feepolicy.Tariffs does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Tariffs) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in stwartchain.feepolicy.Tariffs", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Tariffs) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Tariffs) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Tariffs) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Tariffs) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Tariffs)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Denom)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if len(x.Tariffs) > 0 {
			for _, e := range x.Tariffs {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Tariffs)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Tariffs) > 0 {
			for iNdEx := len(x.Tariffs) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.Tariffs[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0x12
			}
		}
		if len(x.Denom) > 0 {
			i -= len(x.Denom)
			copy(dAtA[i:], x.Denom)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Denom)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Tariffs)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Tariffs: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Tariffs: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Denom = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Tariffs", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Tariffs = append(x.Tariffs, &Tariff{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Tariffs[len(x.Tariffs)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: stwartchain/feepolicy/tariffs.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tariffs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Denom   string    `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Tariffs []*Tariff `protobuf:"bytes,2,rep,name=tariffs,proto3" json:"tariffs,omitempty"`
	Creator string    `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *Tariffs) Reset() {
	*x = Tariffs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stwartchain_feepolicy_tariffs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tariffs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tariffs) ProtoMessage() {}

// Deprecated: Use Tariffs.ProtoReflect.Descriptor instead.
func (*Tariffs) Descriptor() ([]byte, []int) {
	return file_stwartchain_feepolicy_tariffs_proto_rawDescGZIP(), []int{0}
}

func (x *Tariffs) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *Tariffs) GetTariffs() []*Tariff {
	if x != nil {
		return x.Tariffs
	}
	return nil
}

func (x *Tariffs) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_stwartchain_feepolicy_tariffs_proto protoreflect.FileDescriptor

var file_stwartchain_feepolicy_tariffs_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x74, 0x77, 0x61, 0x72, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x66, 0x65,
	0x65, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2f, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x73, 0x74, 0x77, 0x61, 0x72, 0x74, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2e, 0x66, 0x65, 0x65, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x1a, 0x22, 0x73, 0x74,
	0x77, 0x61, 0x72, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x66, 0x65, 0x65, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x2f, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x72, 0x0a, 0x07, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x64,
	0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x6e, 0x6f,
	0x6d, 0x12, 0x37, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x74, 0x77, 0x61, 0x72, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x66, 0x65, 0x65, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x54, 0x61, 0x72, 0x69, 0x66,
	0x66, 0x52, 0x07, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x42, 0xc6, 0x01, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x74, 0x77,
	0x61, 0x72, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x66, 0x65, 0x65, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x42, 0x0c, 0x54, 0x61, 0x72, 0x69, 0x66, 0x66, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x26, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x77, 0x61, 0x72, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2f, 0x66, 0x65, 0x65, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0xa2, 0x02, 0x03, 0x53, 0x46, 0x58,
	0xaa, 0x02, 0x15, 0x53, 0x74, 0x77, 0x61, 0x72, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x46,
	0x65, 0x65, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0xca, 0x02, 0x15, 0x53, 0x74, 0x77, 0x61, 0x72,
	0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x46, 0x65, 0x65, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0xe2, 0x02, 0x21, 0x53, 0x74, 0x77, 0x61, 0x72, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x46,
	0x65, 0x65, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x16, 0x53, 0x74, 0x77, 0x61, 0x72, 0x74, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x3a, 0x3a, 0x46, 0x65, 0x65, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stwartchain_feepolicy_tariffs_proto_rawDescOnce sync.Once
	file_stwartchain_feepolicy_tariffs_proto_rawDescData = file_stwartchain_feepolicy_tariffs_proto_rawDesc
)

func file_stwartchain_feepolicy_tariffs_proto_rawDescGZIP() []byte {
	file_stwartchain_feepolicy_tariffs_proto_rawDescOnce.Do(func() {
		file_stwartchain_feepolicy_tariffs_proto_rawDescData = protoimpl.X.CompressGZIP(file_stwartchain_feepolicy_tariffs_proto_rawDescData)
	})
	return file_stwartchain_feepolicy_tariffs_proto_rawDescData
}

var file_stwartchain_feepolicy_tariffs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stwartchain_feepolicy_tariffs_proto_goTypes = []interface{}{
	(*Tariffs)(nil), // 0: stwartchain.feepolicy.Tariffs
	(*Tariff)(nil),  // 1: stwartchain.feepolicy.Tariff
}
var file_stwartchain_feepolicy_tariffs_proto_depIdxs = []int32{
	1, // 0: stwartchain.feepolicy.Tariffs.tariffs:type_name -> stwartchain.feepolicy.Tariff
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stwartchain_feepolicy_tariffs_proto_init() }
func file_stwartchain_feepolicy_tariffs_proto_init() {
	if File_stwartchain_feepolicy_tariffs_proto != nil {
		return
	}
	file_stwartchain_feepolicy_tariff_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_stwartchain_feepolicy_tariffs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tariffs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stwartchain_feepolicy_tariffs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stwartchain_feepolicy_tariffs_proto_goTypes,
		DependencyIndexes: file_stwartchain_feepolicy_tariffs_proto_depIdxs,
		MessageInfos:      file_stwartchain_feepolicy_tariffs_proto_msgTypes,
	}.Build()
	File_stwartchain_feepolicy_tariffs_proto = out.File
	file_stwartchain_feepolicy_tariffs_proto_rawDesc = nil
	file_stwartchain_feepolicy_tariffs_proto_goTypes = nil
	file_stwartchain_feepolicy_tariffs_proto_depIdxs = nil
}
