swagger: '2.0'
info:
  title: HTTP API Console stwartchain.rates
  name: ''
  description: ''
paths:
  /stwart/rates/addresses:
    get:
      operationId: Query_AddressesAll
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Addresses:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uint64
                    address:
                      type: array
                      items:
                        type: string
                    creator:
                      type: string
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /stwart/rates/addresses/{id}:
    get:
      operationId: Query_Addresses
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Addresses:
                type: object
                properties:
                  id:
                    type: string
                    format: uint64
                  address:
                    type: array
                    items:
                      type: string
                  creator:
                    type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uint64
      tags:
        - Query
  /stwart/rates/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /stwart/rates/rates:
    get:
      operationId: Query_RatesAll
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              rates:
                type: array
                items:
                  type: object
                  properties:
                    denom:
                      type: string
                    rate:
                      type: number
                      format: double
                    creator:
                      type: string
                    decimals:
                      type: integer
                      format: int32
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /stwart/rates/rates/{denom}:
    get:
      operationId: Query_Rates
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              rates:
                type: object
                properties:
                  denom:
                    type: string
                  rate:
                    type: number
                    format: double
                  creator:
                    type: string
                  decimals:
                    type: integer
                    format: int32
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: denom
          in: path
          required: true
          type: string
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
      offset:
        type: string
        format: uint64
      limit:
        type: string
        format: uint64
      count_total:
        type: boolean
      reverse:
        type: boolean
  PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
      total:
        type: string
        format: uint64
  QueryAllAddressesResponse:
    type: object
    properties:
      Addresses:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              format: uint64
            address:
              type: array
              items:
                type: string
            creator:
              type: string
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryAllRatesResponse:
    type: object
    properties:
      rates:
        type: array
        items:
          type: object
          properties:
            denom:
              type: string
            rate:
              type: number
              format: double
            creator:
              type: string
            decimals:
              type: integer
              format: int32
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryGetAddressesResponse:
    type: object
    properties:
      Addresses:
        type: object
        properties:
          id:
            type: string
            format: uint64
          address:
            type: array
            items:
              type: string
          creator:
            type: string
  QueryGetRatesResponse:
    type: object
    properties:
      rates:
        type: object
        properties:
          denom:
            type: string
          rate:
            type: number
            format: double
          creator:
            type: string
          decimals:
            type: integer
            format: int32
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  rates.Addresses:
    type: object
    properties:
      id:
        type: string
        format: uint64
      address:
        type: array
        items:
          type: string
      creator:
        type: string
  rates.Params:
    type: object
  rates.Rates:
    type: object
    properties:
      denom:
        type: string
      rate:
        type: number
        format: double
      creator:
        type: string
      decimals:
        type: integer
        format: int32
  MsgCreateAddressesResponse:
    type: object
    properties:
      id:
        type: string
        format: uint64
  MsgCreateRatesResponse:
    type: object
  MsgDeleteAddressesResponse:
    type: object
  MsgDeleteRatesResponse:
    type: object
  MsgUpdateAddressesResponse:
    type: object
  MsgUpdateParamsResponse:
    type: object
  MsgUpdateRatesResponse:
    type: object
  Params:
    type: object
