// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package polls

import (
	v1beta1 "cosmossdk.io/api/cosmos/base/v1beta1"
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var _ protoreflect.List = (*_PollsParams_1_list)(nil)

type _PollsParams_1_list struct {
	list *[]*v1beta1.Coin
}

func (x *_PollsParams_1_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_PollsParams_1_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfMessage((*x.list)[i].ProtoReflect())
}

func (x *_PollsParams_1_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*v1beta1.Coin)
	(*x.list)[i] = concreteValue
}

func (x *_PollsParams_1_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.Message()
	concreteValue := valueUnwrapped.Interface().(*v1beta1.Coin)
	*x.list = append(*x.list, concreteValue)
}

func (x *_PollsParams_1_list) AppendMutable() protoreflect.Value {
	v := new(v1beta1.Coin)
	*x.list = append(*x.list, v)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_PollsParams_1_list) Truncate(n int) {
	for i := n; i < len(*x.list); i++ {
		(*x.list)[i] = nil
	}
	*x.list = (*x.list)[:n]
}

func (x *_PollsParams_1_list) NewElement() protoreflect.Value {
	v := new(v1beta1.Coin)
	return protoreflect.ValueOfMessage(v.ProtoReflect())
}

func (x *_PollsParams_1_list) IsValid() bool {
	return x.list != nil
}

var (
	md_PollsParams                 protoreflect.MessageDescriptor
	fd_PollsParams_proposerDeposit protoreflect.FieldDescriptor
	fd_PollsParams_minDaysDuration protoreflect.FieldDescriptor
	fd_PollsParams_maxDaysDuration protoreflect.FieldDescriptor
	fd_PollsParams_maxDaysPending  protoreflect.FieldDescriptor
	fd_PollsParams_burnVeto        protoreflect.FieldDescriptor
	fd_PollsParams_creator         protoreflect.FieldDescriptor
)

func init() {
	file_stwartchain_polls_polls_params_proto_init()
	md_PollsParams = File_stwartchain_polls_polls_params_proto.Messages().ByName("PollsParams")
	fd_PollsParams_proposerDeposit = md_PollsParams.Fields().ByName("proposerDeposit")
	fd_PollsParams_minDaysDuration = md_PollsParams.Fields().ByName("minDaysDuration")
	fd_PollsParams_maxDaysDuration = md_PollsParams.Fields().ByName("maxDaysDuration")
	fd_PollsParams_maxDaysPending = md_PollsParams.Fields().ByName("maxDaysPending")
	fd_PollsParams_burnVeto = md_PollsParams.Fields().ByName("burnVeto")
	fd_PollsParams_creator = md_PollsParams.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_PollsParams)(nil)

type fastReflection_PollsParams PollsParams

func (x *PollsParams) ProtoReflect() protoreflect.Message {
	return (*fastReflection_PollsParams)(x)
}

func (x *PollsParams) slowProtoReflect() protoreflect.Message {
	mi := &file_stwartchain_polls_polls_params_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_PollsParams_messageType fastReflection_PollsParams_messageType
var _ protoreflect.MessageType = fastReflection_PollsParams_messageType{}

type fastReflection_PollsParams_messageType struct{}

func (x fastReflection_PollsParams_messageType) Zero() protoreflect.Message {
	return (*fastReflection_PollsParams)(nil)
}
func (x fastReflection_PollsParams_messageType) New() protoreflect.Message {
	return new(fastReflection_PollsParams)
}
func (x fastReflection_PollsParams_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_PollsParams
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_PollsParams) Descriptor() protoreflect.MessageDescriptor {
	return md_PollsParams
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_PollsParams) Type() protoreflect.MessageType {
	return _fastReflection_PollsParams_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_PollsParams) New() protoreflect.Message {
	return new(fastReflection_PollsParams)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_PollsParams) Interface() protoreflect.ProtoMessage {
	return (*PollsParams)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_PollsParams) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if len(x.ProposerDeposit) != 0 {
		value := protoreflect.ValueOfList(&_PollsParams_1_list{list: &x.ProposerDeposit})
		if !f(fd_PollsParams_proposerDeposit, value) {
			return
		}
	}
	if x.MinDaysDuration != "" {
		value := protoreflect.ValueOfString(x.MinDaysDuration)
		if !f(fd_PollsParams_minDaysDuration, value) {
			return
		}
	}
	if x.MaxDaysDuration != "" {
		value := protoreflect.ValueOfString(x.MaxDaysDuration)
		if !f(fd_PollsParams_maxDaysDuration, value) {
			return
		}
	}
	if x.MaxDaysPending != "" {
		value := protoreflect.ValueOfString(x.MaxDaysPending)
		if !f(fd_PollsParams_maxDaysPending, value) {
			return
		}
	}
	if x.BurnVeto != false {
		value := protoreflect.ValueOfBool(x.BurnVeto)
		if !f(fd_PollsParams_burnVeto, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_PollsParams_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_PollsParams) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "stwartchain.polls.PollsParams.proposerDeposit":
		return len(x.ProposerDeposit) != 0
	case "stwartchain.polls.PollsParams.minDaysDuration":
		return x.MinDaysDuration != ""
	case "stwartchain.polls.PollsParams.maxDaysDuration":
		return x.MaxDaysDuration != ""
	case "stwartchain.polls.PollsParams.maxDaysPending":
		return x.MaxDaysPending != ""
	case "stwartchain.polls.PollsParams.burnVeto":
		return x.BurnVeto != false
	case "stwartchain.polls.PollsParams.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: stwartchain.polls.PollsParams"))
		}
		panic(fmt.Errorf("message stwartchain.polls.PollsParams does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PollsParams) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "stwartchain.polls.PollsParams.proposerDeposit":
		x.ProposerDeposit = nil
	case "stwartchain.polls.PollsParams.minDaysDuration":
		x.MinDaysDuration = ""
	case "stwartchain.polls.PollsParams.maxDaysDuration":
		x.MaxDaysDuration = ""
	case "stwartchain.polls.PollsParams.maxDaysPending":
		x.MaxDaysPending = ""
	case "stwartchain.polls.PollsParams.burnVeto":
		x.BurnVeto = false
	case "stwartchain.polls.PollsParams.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: stwartchain.polls.PollsParams"))
		}
		panic(fmt.Errorf("message stwartchain.polls.PollsParams does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_PollsParams) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "stwartchain.polls.PollsParams.proposerDeposit":
		if len(x.ProposerDeposit) == 0 {
			return protoreflect.ValueOfList(&_PollsParams_1_list{})
		}
		listValue := &_PollsParams_1_list{list: &x.ProposerDeposit}
		return protoreflect.ValueOfList(listValue)
	case "stwartchain.polls.PollsParams.minDaysDuration":
		value := x.MinDaysDuration
		return protoreflect.ValueOfString(value)
	case "stwartchain.polls.PollsParams.maxDaysDuration":
		value := x.MaxDaysDuration
		return protoreflect.ValueOfString(value)
	case "stwartchain.polls.PollsParams.maxDaysPending":
		value := x.MaxDaysPending
		return protoreflect.ValueOfString(value)
	case "stwartchain.polls.PollsParams.burnVeto":
		value := x.BurnVeto
		return protoreflect.ValueOfBool(value)
	case "stwartchain.polls.PollsParams.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: stwartchain.polls.PollsParams"))
		}
		panic(fmt.Errorf("message stwartchain.polls.PollsParams does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PollsParams) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "stwartchain.polls.PollsParams.proposerDeposit":
		lv := value.List()
		clv := lv.(*_PollsParams_1_list)
		x.ProposerDeposit = *clv.list
	case "stwartchain.polls.PollsParams.minDaysDuration":
		x.MinDaysDuration = value.Interface().(string)
	case "stwartchain.polls.PollsParams.maxDaysDuration":
		x.MaxDaysDuration = value.Interface().(string)
	case "stwartchain.polls.PollsParams.maxDaysPending":
		x.MaxDaysPending = value.Interface().(string)
	case "stwartchain.polls.PollsParams.burnVeto":
		x.BurnVeto = value.Bool()
	case "stwartchain.polls.PollsParams.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: stwartchain.polls.PollsParams"))
		}
		panic(fmt.Errorf("message stwartchain.polls.PollsParams does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PollsParams) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "stwartchain.polls.PollsParams.proposerDeposit":
		if x.ProposerDeposit == nil {
			x.ProposerDeposit = []*v1beta1.Coin{}
		}
		value := &_PollsParams_1_list{list: &x.ProposerDeposit}
		return protoreflect.ValueOfList(value)
	case "stwartchain.polls.PollsParams.minDaysDuration":
		panic(fmt.Errorf("field minDaysDuration of message stwartchain.polls.PollsParams is not mutable"))
	case "stwartchain.polls.PollsParams.maxDaysDuration":
		panic(fmt.Errorf("field maxDaysDuration of message stwartchain.polls.PollsParams is not mutable"))
	case "stwartchain.polls.PollsParams.maxDaysPending":
		panic(fmt.Errorf("field maxDaysPending of message stwartchain.polls.PollsParams is not mutable"))
	case "stwartchain.polls.PollsParams.burnVeto":
		panic(fmt.Errorf("field burnVeto of message stwartchain.polls.PollsParams is not mutable"))
	case "stwartchain.polls.PollsParams.creator":
		panic(fmt.Errorf("field creator of message stwartchain.polls.PollsParams is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: stwartchain.polls.PollsParams"))
		}
		panic(fmt.Errorf("message stwartchain.polls.PollsParams does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_PollsParams) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "stwartchain.polls.PollsParams.proposerDeposit":
		list := []*v1beta1.Coin{}
		return protoreflect.ValueOfList(&_PollsParams_1_list{list: &list})
	case "stwartchain.polls.PollsParams.minDaysDuration":
		return protoreflect.ValueOfString("")
	case "stwartchain.polls.PollsParams.maxDaysDuration":
		return protoreflect.ValueOfString("")
	case "stwartchain.polls.PollsParams.maxDaysPending":
		return protoreflect.ValueOfString("")
	case "stwartchain.polls.PollsParams.burnVeto":
		return protoreflect.ValueOfBool(false)
	case "stwartchain.polls.PollsParams.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: stwartchain.polls.PollsParams"))
		}
		panic(fmt.Errorf("message stwartchain.polls.PollsParams does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_PollsParams) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in stwartchain.polls.PollsParams", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_PollsParams) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PollsParams) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_PollsParams) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_PollsParams) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*PollsParams)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if len(x.ProposerDeposit) > 0 {
			for _, e := range x.ProposerDeposit {
				l = options.Size(e)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		l = len(x.MinDaysDuration)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.MaxDaysDuration)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.MaxDaysPending)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.BurnVeto {
			n += 2
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*PollsParams)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x32
		}
		if x.BurnVeto {
			i--
			if x.BurnVeto {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x28
		}
		if len(x.MaxDaysPending) > 0 {
			i -= len(x.MaxDaysPending)
			copy(dAtA[i:], x.MaxDaysPending)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MaxDaysPending)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.MaxDaysDuration) > 0 {
			i -= len(x.MaxDaysDuration)
			copy(dAtA[i:], x.MaxDaysDuration)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MaxDaysDuration)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.MinDaysDuration) > 0 {
			i -= len(x.MinDaysDuration)
			copy(dAtA[i:], x.MinDaysDuration)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MinDaysDuration)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.ProposerDeposit) > 0 {
			for iNdEx := len(x.ProposerDeposit) - 1; iNdEx >= 0; iNdEx-- {
				encoded, err := options.Marshal(x.ProposerDeposit[iNdEx])
				if err != nil {
					return protoiface.MarshalOutput{
						NoUnkeyedLiterals: input.NoUnkeyedLiterals,
						Buf:               input.Buf,
					}, err
				}
				i -= len(encoded)
				copy(dAtA[i:], encoded)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
				i--
				dAtA[i] = 0xa
			}
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*PollsParams)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PollsParams: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PollsParams: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ProposerDeposit", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ProposerDeposit = append(x.ProposerDeposit, &v1beta1.Coin{})
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.ProposerDeposit[len(x.ProposerDeposit)-1]); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MinDaysDuration", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MinDaysDuration = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MaxDaysDuration", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MaxDaysDuration = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MaxDaysPending", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MaxDaysPending = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BurnVeto", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.BurnVeto = bool(v != 0)
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: stwartchain/polls/polls_params.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PollsParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProposerDeposit []*v1beta1.Coin `protobuf:"bytes,1,rep,name=proposerDeposit,proto3" json:"proposerDeposit,omitempty"`
	MinDaysDuration string          `protobuf:"bytes,2,opt,name=minDaysDuration,proto3" json:"minDaysDuration,omitempty"`
	MaxDaysDuration string          `protobuf:"bytes,3,opt,name=maxDaysDuration,proto3" json:"maxDaysDuration,omitempty"`
	MaxDaysPending  string          `protobuf:"bytes,4,opt,name=maxDaysPending,proto3" json:"maxDaysPending,omitempty"`
	BurnVeto        bool            `protobuf:"varint,5,opt,name=burnVeto,proto3" json:"burnVeto,omitempty"`
	Creator         string          `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *PollsParams) Reset() {
	*x = PollsParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stwartchain_polls_polls_params_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollsParams) ProtoMessage() {}

// Deprecated: Use PollsParams.ProtoReflect.Descriptor instead.
func (*PollsParams) Descriptor() ([]byte, []int) {
	return file_stwartchain_polls_polls_params_proto_rawDescGZIP(), []int{0}
}

func (x *PollsParams) GetProposerDeposit() []*v1beta1.Coin {
	if x != nil {
		return x.ProposerDeposit
	}
	return nil
}

func (x *PollsParams) GetMinDaysDuration() string {
	if x != nil {
		return x.MinDaysDuration
	}
	return ""
}

func (x *PollsParams) GetMaxDaysDuration() string {
	if x != nil {
		return x.MaxDaysDuration
	}
	return ""
}

func (x *PollsParams) GetMaxDaysPending() string {
	if x != nil {
		return x.MaxDaysPending
	}
	return ""
}

func (x *PollsParams) GetBurnVeto() bool {
	if x != nil {
		return x.BurnVeto
	}
	return false
}

func (x *PollsParams) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_stwartchain_polls_polls_params_proto protoreflect.FileDescriptor

var file_stwartchain_polls_polls_params_proto_rawDesc = []byte{
	0x0a, 0x24, 0x73, 0x74, 0x77, 0x61, 0x72, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x6f,
	0x6c, 0x6c, 0x73, 0x2f, 0x70, 0x6f, 0x6c, 0x6c, 0x73, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73, 0x74, 0x77, 0x61, 0x72, 0x74, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x2e, 0x70, 0x6f, 0x6c, 0x6c, 0x73, 0x1a, 0x1e, 0x63, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x63,
	0x6f, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x8a, 0x02, 0x0a, 0x0b, 0x50, 0x6f, 0x6c, 0x6c, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x49, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x44, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x43,
	0x6f, 0x69, 0x6e, 0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x65, 0x72, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x69,
	0x6e, 0x44, 0x61, 0x79, 0x73, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x6d, 0x69, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x44, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x44, 0x61, 0x79, 0x73, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6d,
	0x61, 0x78, 0x44, 0x61, 0x79, 0x73, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26,
	0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x44, 0x61, 0x79, 0x73, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x44, 0x61, 0x79, 0x73, 0x50,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x72, 0x6e, 0x56, 0x65,
	0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x62, 0x75, 0x72, 0x6e, 0x56, 0x65,
	0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x42, 0xb2, 0x01, 0x0a,
	0x15, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x74, 0x77, 0x61, 0x72, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x70, 0x6f, 0x6c, 0x6c, 0x73, 0x42, 0x10, 0x50, 0x6f, 0x6c, 0x6c, 0x73, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x22, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x77,
	0x61, 0x72, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x6f, 0x6c, 0x6c, 0x73, 0xa2, 0x02,
	0x03, 0x53, 0x50, 0x58, 0xaa, 0x02, 0x11, 0x53, 0x74, 0x77, 0x61, 0x72, 0x74, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x73, 0xca, 0x02, 0x11, 0x53, 0x74, 0x77, 0x61, 0x72,
	0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x50, 0x6f, 0x6c, 0x6c, 0x73, 0xe2, 0x02, 0x1d, 0x53,
	0x74, 0x77, 0x61, 0x72, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x50, 0x6f, 0x6c, 0x6c, 0x73,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x12, 0x53,
	0x74, 0x77, 0x61, 0x72, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x3a, 0x3a, 0x50, 0x6f, 0x6c, 0x6c,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stwartchain_polls_polls_params_proto_rawDescOnce sync.Once
	file_stwartchain_polls_polls_params_proto_rawDescData = file_stwartchain_polls_polls_params_proto_rawDesc
)

func file_stwartchain_polls_polls_params_proto_rawDescGZIP() []byte {
	file_stwartchain_polls_polls_params_proto_rawDescOnce.Do(func() {
		file_stwartchain_polls_polls_params_proto_rawDescData = protoimpl.X.CompressGZIP(file_stwartchain_polls_polls_params_proto_rawDescData)
	})
	return file_stwartchain_polls_polls_params_proto_rawDescData
}

var file_stwartchain_polls_polls_params_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stwartchain_polls_polls_params_proto_goTypes = []interface{}{
	(*PollsParams)(nil),  // 0: stwartchain.polls.PollsParams
	(*v1beta1.Coin)(nil), // 1: cosmos.base.v1beta1.Coin
}
var file_stwartchain_polls_polls_params_proto_depIdxs = []int32{
	1, // 0: stwartchain.polls.PollsParams.proposerDeposit:type_name -> cosmos.base.v1beta1.Coin
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stwartchain_polls_polls_params_proto_init() }
func file_stwartchain_polls_polls_params_proto_init() {
	if File_stwartchain_polls_polls_params_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stwartchain_polls_polls_params_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollsParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stwartchain_polls_polls_params_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stwartchain_polls_polls_params_proto_goTypes,
		DependencyIndexes: file_stwartchain_polls_polls_params_proto_depIdxs,
		MessageInfos:      file_stwartchain_polls_polls_params_proto_msgTypes,
	}.Build()
	File_stwartchain_polls_polls_params_proto = out.File
	file_stwartchain_polls_polls_params_proto_rawDesc = nil
	file_stwartchain_polls_polls_params_proto_goTypes = nil
	file_stwartchain_polls_polls_params_proto_depIdxs = nil
}
