// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stwartchain/stats/user_stats.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UserStats struct {
	CountUniqueActiveUsers uint64 `protobuf:"varint,1,opt,name=countUniqueActiveUsers,proto3" json:"countUniqueActiveUsers,omitempty"`
	CountNewUsers          uint64 `protobuf:"varint,2,opt,name=countNewUsers,proto3" json:"countNewUsers,omitempty"`
}

func (m *UserStats) Reset()         { *m = UserStats{} }
func (m *UserStats) String() string { return proto.CompactTextString(m) }
func (*UserStats) ProtoMessage()    {}
func (*UserStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1e0ce1e85a621b0, []int{0}
}
func (m *UserStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStats.Merge(m, src)
}
func (m *UserStats) XXX_Size() int {
	return m.Size()
}
func (m *UserStats) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStats.DiscardUnknown(m)
}

var xxx_messageInfo_UserStats proto.InternalMessageInfo

func (m *UserStats) GetCountUniqueActiveUsers() uint64 {
	if m != nil {
		return m.CountUniqueActiveUsers
	}
	return 0
}

func (m *UserStats) GetCountNewUsers() uint64 {
	if m != nil {
		return m.CountNewUsers
	}
	return 0
}

func init() {
	proto.RegisterType((*UserStats)(nil), "stwartchain.stats.UserStats")
}

func init() {
	proto.RegisterFile("stwartchain/stats/user_stats.proto", fileDescriptor_b1e0ce1e85a621b0)
}

var fileDescriptor_b1e0ce1e85a621b0 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x2e, 0x29, 0x4f,
	0x2c, 0x2a, 0x49, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x2f, 0x2e, 0x49, 0x2c, 0x29, 0xd6, 0x2f, 0x2d,
	0x4e, 0x2d, 0x8a, 0x07, 0x33, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x04, 0x91, 0xd4, 0xe8,
	0x81, 0x25, 0x94, 0x32, 0xb9, 0x38, 0x43, 0x8b, 0x53, 0x8b, 0x82, 0x41, 0x1c, 0x21, 0x33, 0x2e,
	0xb1, 0xe4, 0xfc, 0xd2, 0xbc, 0x92, 0xd0, 0xbc, 0xcc, 0xc2, 0xd2, 0x54, 0xc7, 0xe4, 0x92, 0xcc,
	0xb2, 0x54, 0x90, 0x6c, 0xb1, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x0e, 0x59, 0x21, 0x15,
	0x2e, 0x5e, 0xb0, 0x8c, 0x5f, 0x6a, 0x39, 0x44, 0x39, 0x13, 0x58, 0x39, 0xaa, 0xa0, 0x53, 0xf4,
	0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c,
	0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0x39, 0xa6, 0x67, 0x96, 0xe4, 0x24,
	0x26, 0x81, 0x9c, 0x94, 0x03, 0x72, 0xa0, 0x5e, 0x49, 0x6a, 0x72, 0x86, 0x7e, 0x66, 0x56, 0x66,
	0xbe, 0x7e, 0x2e, 0xc8, 0x3b, 0x49, 0x89, 0xc9, 0xd9, 0xa9, 0x79, 0x29, 0xfa, 0x10, 0xe7, 0xeb,
	0x42, 0xfc, 0x58, 0x01, 0xf5, 0x65, 0x49, 0x65, 0x41, 0x6a, 0x71, 0x12, 0x1b, 0xd8, 0x87, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xc5, 0x24, 0xfa, 0x07, 0x01, 0x00, 0x00,
}

func (m *UserStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CountNewUsers != 0 {
		i = encodeVarintUserStats(dAtA, i, uint64(m.CountNewUsers))
		i--
		dAtA[i] = 0x10
	}
	if m.CountUniqueActiveUsers != 0 {
		i = encodeVarintUserStats(dAtA, i, uint64(m.CountUniqueActiveUsers))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintUserStats(dAtA []byte, offset int, v uint64) int {
	offset -= sovUserStats(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UserStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CountUniqueActiveUsers != 0 {
		n += 1 + sovUserStats(uint64(m.CountUniqueActiveUsers))
	}
	if m.CountNewUsers != 0 {
		n += 1 + sovUserStats(uint64(m.CountNewUsers))
	}
	return n
}

func sovUserStats(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUserStats(x uint64) (n int) {
	return sovUserStats(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UserStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUserStats
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CountUniqueActiveUsers", wireType)
			}
			m.CountUniqueActiveUsers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserStats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CountUniqueActiveUsers |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CountNewUsers", wireType)
			}
			m.CountNewUsers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUserStats
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CountNewUsers |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipUserStats(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUserStats
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUserStats(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUserStats
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUserStats
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUserStats
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUserStats
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUserStats
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUserStats
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUserStats        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUserStats          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUserStats = fmt.Errorf("proto: unexpected end of group")
)
