swagger: '2.0'
info:
  title: HTTP API Console stwartchain.users
  name: ''
  description: ''
paths:
  /stwart/users/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /stwart/users/stats:
    get:
      operationId: Query_StatsAll
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              stats:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                    dailyStats:
                      type: object
                      properties:
                        countUniqueActiveUsers:
                          type: string
                          format: uint64
                        countNewUsers:
                          type: string
                          format: uint64
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /stwart/users/stats/{date}:
    get:
      operationId: Query_Stats
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              stats:
                type: object
                properties:
                  date:
                    type: string
                  dailyStats:
                    type: object
                    properties:
                      countUniqueActiveUsers:
                        type: string
                        format: uint64
                      countNewUsers:
                        type: string
                        format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: date
          in: path
          required: true
          type: string
      tags:
        - Query
  /stwart/users/stats_by_date/{startDate}/{endDate}:
    get:
      operationId: Query_StatsByDate
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              stats:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                    dailyStats:
                      type: object
                      properties:
                        countUniqueActiveUsers:
                          type: string
                          format: uint64
                        countNewUsers:
                          type: string
                          format: uint64
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: startDate
          in: path
          required: true
          type: string
        - name: endDate
          in: path
          required: true
          type: string
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /stwart/users/total:
    get:
      operationId: Query_Total
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              count:
                type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /stwart/users/unique_users:
    get:
      operationId: Query_UniqueUsersAll
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              uniqueUsers:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                    uniqueUserAddresses:
                      type: object
                      properties:
                        addresses:
                          type: array
                          items:
                            type: string
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /stwart/users/unique_users/{date}:
    get:
      operationId: Query_UniqueUsers
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              uniqueUsers:
                type: object
                properties:
                  date:
                    type: string
                  uniqueUserAddresses:
                    type: object
                    properties:
                      addresses:
                        type: array
                        items:
                          type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: date
          in: path
          required: true
          type: string
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  DailyStats:
    type: object
    properties:
      countUniqueActiveUsers:
        type: string
        format: uint64
      countNewUsers:
        type: string
        format: uint64
  PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
      offset:
        type: string
        format: uint64
      limit:
        type: string
        format: uint64
      count_total:
        type: boolean
      reverse:
        type: boolean
  PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
      total:
        type: string
        format: uint64
  QueryAllStatsResponse:
    type: object
    properties:
      stats:
        type: array
        items:
          type: object
          properties:
            date:
              type: string
            dailyStats:
              type: object
              properties:
                countUniqueActiveUsers:
                  type: string
                  format: uint64
                countNewUsers:
                  type: string
                  format: uint64
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryAllUniqueUsersResponse:
    type: object
    properties:
      uniqueUsers:
        type: array
        items:
          type: object
          properties:
            date:
              type: string
            uniqueUserAddresses:
              type: object
              properties:
                addresses:
                  type: array
                  items:
                    type: string
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryGetStatsResponse:
    type: object
    properties:
      stats:
        type: object
        properties:
          date:
            type: string
          dailyStats:
            type: object
            properties:
              countUniqueActiveUsers:
                type: string
                format: uint64
              countNewUsers:
                type: string
                format: uint64
  QueryGetUniqueUsersResponse:
    type: object
    properties:
      uniqueUsers:
        type: object
        properties:
          date:
            type: string
          uniqueUserAddresses:
            type: object
            properties:
              addresses:
                type: array
                items:
                  type: string
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  QueryStatsByDateResponse:
    type: object
    properties:
      stats:
        type: array
        items:
          type: object
          properties:
            date:
              type: string
            dailyStats:
              type: object
              properties:
                countUniqueActiveUsers:
                  type: string
                  format: uint64
                countNewUsers:
                  type: string
                  format: uint64
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryTotalResponse:
    type: object
    properties:
      count:
        type: string
  UniqueUserAddresses:
    type: object
    properties:
      addresses:
        type: array
        items:
          type: string
  users.Params:
    type: object
  users.Stats:
    type: object
    properties:
      date:
        type: string
      dailyStats:
        type: object
        properties:
          countUniqueActiveUsers:
            type: string
            format: uint64
          countNewUsers:
            type: string
            format: uint64
  users.UniqueUsers:
    type: object
    properties:
      date:
        type: string
      uniqueUserAddresses:
        type: object
        properties:
          addresses:
            type: array
            items:
              type: string
  MsgUpdateParamsResponse:
    type: object
  Params:
    type: object
