swagger: '2.0'
info:
  title: HTTP API Console stwartchain.systemrewards
  name: ''
  description: ''
paths:
  /stwart/systemrewards/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /stwart/systemrewards/stats:
    get:
      operationId: Query_StatsAll
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              stats:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                    dailyStats:
                      type: object
                      properties:
                        reward:
                          type: array
                          items:
                            type: object
                            properties:
                              denom:
                                type: string
                              amount:
                                type: string
                        count:
                          type: string
                          format: uint64
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /stwart/systemrewards/stats/{date}:
    get:
      operationId: Query_Stats
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              stats:
                type: object
                properties:
                  date:
                    type: string
                  dailyStats:
                    type: object
                    properties:
                      reward:
                        type: array
                        items:
                          type: object
                          properties:
                            denom:
                              type: string
                            amount:
                              type: string
                      count:
                        type: string
                        format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: date
          in: path
          required: true
          type: string
      tags:
        - Query
  /stwart/systemrewards/stats_by_date/{startDate}/{endDate}:
    get:
      operationId: Query_StatsByDate
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              stats:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                    dailyStats:
                      type: object
                      properties:
                        reward:
                          type: array
                          items:
                            type: object
                            properties:
                              denom:
                                type: string
                              amount:
                                type: string
                        count:
                          type: string
                          format: uint64
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: startDate
          in: path
          required: true
          type: string
        - name: endDate
          in: path
          required: true
          type: string
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  Coin:
    type: object
    properties:
      denom:
        type: string
      amount:
        type: string
  DailyStats:
    type: object
    properties:
      reward:
        type: array
        items:
          type: object
          properties:
            denom:
              type: string
            amount:
              type: string
      count:
        type: string
        format: uint64
  PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
      offset:
        type: string
        format: uint64
      limit:
        type: string
        format: uint64
      count_total:
        type: boolean
      reverse:
        type: boolean
  PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
      total:
        type: string
        format: uint64
  QueryAllStatsResponse:
    type: object
    properties:
      stats:
        type: array
        items:
          type: object
          properties:
            date:
              type: string
            dailyStats:
              type: object
              properties:
                reward:
                  type: array
                  items:
                    type: object
                    properties:
                      denom:
                        type: string
                      amount:
                        type: string
                count:
                  type: string
                  format: uint64
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryGetStatsResponse:
    type: object
    properties:
      stats:
        type: object
        properties:
          date:
            type: string
          dailyStats:
            type: object
            properties:
              reward:
                type: array
                items:
                  type: object
                  properties:
                    denom:
                      type: string
                    amount:
                      type: string
              count:
                type: string
                format: uint64
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  QueryStatsByDateResponse:
    type: object
    properties:
      stats:
        type: array
        items:
          type: object
          properties:
            date:
              type: string
            dailyStats:
              type: object
              properties:
                reward:
                  type: array
                  items:
                    type: object
                    properties:
                      denom:
                        type: string
                      amount:
                        type: string
                count:
                  type: string
                  format: uint64
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  systemrewards.Params:
    type: object
  systemrewards.Stats:
    type: object
    properties:
      date:
        type: string
      dailyStats:
        type: object
        properties:
          reward:
            type: array
            items:
              type: object
              properties:
                denom:
                  type: string
                amount:
                  type: string
          count:
            type: string
            format: uint64
  MsgUpdateParamsResponse:
    type: object
  Params:
    type: object
